export default {

    HANDLE_MODAL: 'HANDLE_MODAL',

    FETCH_POSTS: 'FETCH_POSTS',
    FETCH_MEDIAS: 'FETCH_MEDIAS',

    FETCH_PROGRAMS: 'FETCH_PROGRAMS',


    PROGRAMS_GRADE: 'PROGRAMS_GRADE',
    PROGRAMS_FIELD: 'PROGRAMS_FIELD',

    LOGGED: 'LOGGED'
};


