export default {

    HANDLE_PAGE_NUMBER: 'HANDLE_PAGE_NUMBER',

    HANDLE_POSTS: 'HANDLE_POSTS',

    HANDLE_MODAL: 'HANDLE_MODAL',
    HANDLE_SIZE: 'HANDLE_SIZE',
    HANDLE_TAB: 'HANDLE_TAB',

    FETCH_POSTS: 'FETCH_POSTS',
    FETCH_MEDIAS: 'FETCH_MEDIAS',

    FETCH_PROGRAMS: 'FETCH_PROGRAMS',


    PROGRAMS_GRADE: 'PROGRAMS_GRADE',
    PROGRAMS_FIELD: 'PROGRAMS_FIELD',

    LOGGED: 'LOGGED'
};


